### PR TITLE
Issues/181 better sphinx config

### PR DESCRIPTION
**Pull request by lizconlan**
Bit of WIP but jumping the gun for easier internal discussions...

Towards trying to run a single `searchd` instance per server rather than having to wrangle one per app.

Open to the idea of squashing the 3 'Override rake task ...' commits

### CODE REVIEW

**Comment by stevenday** [comment]
This looks great. I haven't run it locally yet, but I would definitely merge the three rake task commits as a first thing.

The only other thing that bothers me slightly on a first read of this is that we assume that certain config file sections will always be x lines long. I know it's always going to be an inexact science, but perhaps we could check the content of some of those lines too before we modify the files, to be sure it's doing the right thing? Otherwise I can see debugging it when somehow TS adds another line being a bit of a nightmare.

**Comment by stevenday** [comment]
I've been talking to ian about implementing the other side of this, which is to run a single sphinx daemon through puppet, and make sure it picks up all of the individual config files and combines them into one (turns out, sphinx's config can start with a shebang, and then it'll execute it and process the output!). 

In doing so, I wondered whether all this hijacking of thinking sphinx is worth it, or whether we should just create the config via mysociety's ugly files instead? They'd have access to all the right info, and the meat of the config (the SQL query) should be the same throughout (or it could be setup different in some if statements if needed). 

The only thing we'd need to do is remember to always run `ts:index` with the flag that says "don't generate the config again".

Can you see any obvious flaws @lizconlan?

**Comment by lizconlan** [comment]
[ much too late to be useful :crying_cat_face: ]

If we can make it work that way around, I can't think of any reason why not - is there some way of overriding `ts:index` so that it defaults to skipping the config generation or is that too optimistic?

(And yes, running sphinx is a pain - not sure whether it's practical to swap it out and still maintain a fork of the OpenAustralia code though)

**Comment by stevenday** [comment]
Closing this as #192 is now merged

**Pull request closed without merging**
